development:
    adapter: postgresql
    database: vidsync_prototype_development
    host: localhost
    pool: 5
    timeout: 5000
    username: postgres
    password: postgres

test:
    adapter: postgresql
    database: vidsync_prototype_test
    host: localhost
    pool: 5
    timeout: 5000
    username: postgres
    password: postgres
